### ISSUE TITLE
Location of the article at Microsoft Docs:

### ISSUE THREAD

**Issue by Spaanseh** [Edu4rdSHL/microsoft-giveaway-books#2]
https://docs.microsoft.com/archive/blogs/mssmallbiz/free-thats-right-im-giving-away-millions-of-free-microsoft-ebooks-again-including-windows-10-office-365-office-2016-power-bi-azure-windows-8-1-office-2013-sharepoint-2016-sha

So it's looking kind of alike, but not the same thing. Anyway, all offered books are still for download there.

**Comment by Edu4rdSHL** [comment]
Hello, I have fixed the script and also uploaded the lists to the [files](https://github.com/Edu4rdSHL/microsoft-giveaway-books/tree/master/files) folder and will use them for downloads, that way the current problem is solved.

Thanks for reporting.
